fix(build): add fail fast flag to all bash scripts

diff --git a/scripts/bump-version b/scripts/bump-version
--- a/scripts/bump-version
+++ b/scripts/bump-version
@@ -7,6 +7,9 @@
 # 
 # Remember to run this script from the root of the project!
 
+# Fail fast
+set -e
+
 # ANSI colour codes so we can highlight text in the terminal
 colour_red="\033[0;31m"
 colour_green="\033[0;32m"
@@ -103,9 +106,9 @@ function push_to_git {
 	# NOTE: Do not tag the commit, as the CI will then not create a release
 	# Pre-releases will contain a dash in their version
 	if [[ $new_release_tag =~ "-" ]]; then
-		git commit --signoff -m "chore(release): prerelease $new_release_tag"
+		git commit -m "chore(release): prerelease $new_release_tag"
 	else
-		git commit --signoff -m "chore(release): release $new_release_tag"
+		git commit -m "chore(release): release $new_release_tag"
 	fi
 	
 	# Push the changes
